### ISSUE TITLE
[Suggestion] Add option to hide "Discover More" section

### ISSUE THREAD

**Issue by aubymori** [insin/control-panel-for-twitter#310] opened 2023-06-03 17:12 UTC
Recently, Twitter has been showing this useless "Discover More" section below replies, and I can't find a way to hide it with CSS, so it'd be really appreciated if you could implement an option to hide this section from the replies.
![image](https://github.com/insin/control-panel-for-twitter/assets/44238627/fb1a14fa-f96a-41cc-b133-f819e67d3c8e)

**Comment by aubymori** [comment] 2023-06-03 17:12
Also, this seems to only happen in the media viewer, on the right. When I open the Tweet normally, this section doesn't show up.

**Comment by insin** [comment] 2023-06-04 08:17
There's already a feature for this but they keep moving it around and changing it - will try to fix it in its new location

**Comment by aubymori** [comment] 2023-06-04 16:06
Thanks!

**Comment by biggestsonicfan** [comment] 2023-06-05 19:45
It looks like if you open a Media tweet with not enough engagement to fill the screen, Twitter is inserting this as filler :confounded:

**Comment by ketsuban** [comment] 2023-06-20 19:07
I'm seeing this on replies with images or quote-tweets; plain replies don't have it.

**Comment by biggestsonicfan** [comment] 2023-06-20 20:27
Just installed the latest userscript and I also see them.

**Comment by insin** [comment] 2023-06-20 22:59
@ketsuban @biggestsonicfan could you provide some screenshots and links to tweets you're still seeing them on? It would be useful when trying to figure out why they're still appearing.

**Comment by ketsuban** [comment] 2023-06-20 23:36
Sure.

https://twitter.com/XC_Enel/status/1671229689497518101
https://twitter.com/ManishEarth/status/1671212496273969152
https://twitter.com/notrevenant/status/1671184957308383232

**Comment by insin** [comment] 2023-06-21 06:06
Those are all getting hidden for me using the latest version of the extension (v3.8.1) or user script (v112)

![firefox_GRlSBYIWpa](https://github.com/insin/control-panel-for-twitter/assets/226692/73220ab0-0c56-4910-b2bd-d7f20aeaec87)

![firefox_sa0gzGiDDr](https://github.com/insin/control-panel-for-twitter/assets/226692/18b50adb-9a8f-4371-9c58-d9307af38ddd)

![firefox_4JkDpg0FBy](https://github.com/insin/control-panel-for-twitter/assets/226692/da6f2a4e-46b8-4a0d-acc5-e817b3caa7f2)

![firefox_XCP44Hq0dt](https://github.com/insin/control-panel-for-twitter/assets/226692/0f5f1dfe-9735-44fd-b56f-a33cf9a18963)

**Comment by ketsuban** [comment] 2023-06-21 13:05
Hm. I thought I had the most recent version but I just now saw I'm apparently still on 3.6. I'll try and make it update and see if that fixes it. Sorry to waste your time like this.

**Comment by biggestsonicfan** [comment] 2023-06-23 19:59
The update may have resolved it for ketsuban, but the issue persists for me on 112 userscript :(

**Comment by biggestsonicfan** [comment] 2023-06-28 03:41
The 113 script appears to be working with a caveat: It's still showing "Discover More" tweets of the same user.
[Example](https://twitter.com/amicoamiami/status/1673896900238647296)
![Screenshot_20230627_204035](https://github.com/insin/control-panel-for-twitter/assets/9744201/d191c6f7-e38f-4bb6-af48-506c40b759c7)

**Comment by biggestsonicfan** [comment] 2023-07-09 01:26
No dice yet with 114. I don't know why I specifically am having the issue, hmm... maybe a conflict I will investigate...

**Comment by biggestsonicfan** [comment] 2023-07-18 09:11
Did a reinstall of 117, seems to have done the trick. I only see "Discover More" of the same user now, which is acceptable!

**Comment by insin** [comment] 2023-07-18 09:25
Could you link to some tweets you're still seeing it on?

Setting `debug = true` at the top of the script should let you see what it's seeing in the console

It should look something like this when you navigate to a tweet and it has Discover More tweets to hide:

![image](https://github.com/insin/control-panel-for-twitter/assets/226692/cd3c9805-1c1a-4a4e-b6e0-18097344bea2)

**Comment by biggestsonicfan** [comment] 2023-07-20 01:37
Using our old friend https://twitter.com/notrevenant/status/1671184957308383232
![Screenshot_20230719_183630](https://github.com/insin/control-panel-for-twitter/assets/9744201/1712bd90-d0cf-472e-8733-de4eeb32d2bf)

**Comment by nomakewan** [comment] 2023-07-29 08:40
Joining in to confirm this is still happening with the Firefox addon 3.13.1.

Example tweet: https://twitter.com/yn_szk/status/1684851187261247488/photo/1

![tweetdiscover](https://github.com/insin/control-panel-for-twitter/assets/11485516/34856311-501e-4324-80ef-c97ed481ae20)

I don't see a way to enable debug mode in the addon.

**Comment by biggestsonicfan** [comment] 2023-08-04 01:10
We've had quite a few releases in the last two weeks and I know this is a backburner issue compared to what's come up recently but can you at least confirm the issue is reproducable on your end?

Remember, it's not just _opening_ a media tweet, you must also _enlarge an image_.

**Comment by insin** [comment] 2023-08-04 20:57
Are any of you hiding the Messages drawer? And if you unhide it, is it open?

**Comment by nomakewan** [comment] 2023-08-04 22:09
I do not hide the Messages drawer, no.

**Comment by biggestsonicfan** [comment] 2023-08-05 10:31
It is hidden by default 
https://github.com/insin/control-panel-for-twitter/blob/eed8873d7b68ad6397a25872e4555dde6bf7698a/script.js#L105C28-L105C28

So yes. This is with the message drawer unhidden:
![Screenshot_20230805_032728](https://github.com/insin/control-panel-for-twitter/assets/9744201/9251e7b0-9b25-477d-9f23-a70496224b51)

You can faintly see "Messages" in the lower right corner.

This is with the Messages drawer open....

![Screenshot_20230805_032914](https://github.com/insin/control-panel-for-twitter/assets/9744201/0a34ed12-5074-43bc-8e25-12d5a1df6f11)

So as your state in your new issue "Media modal timeline detection fails if the Messages drawer is open" is 100% correct.

**Comment by nomakewan** [comment] 2023-08-05 13:33
Ah, I see. I misunderstood what "messages drawer" is.

Can confirm that unhiding it, it was open. Closed it, rehid the drawer, and the issue is resolved. Thank you!

**Closed** 2023-08-07 03:29 UTC
Labels: twitter-change

**Comment by grndkntrl** [comment] 2023-08-30 23:36
Hi,

It seems as though Twitter has changed something in the last few hours and the "_Discover more_" section is back again:

![image](https://github.com/insin/control-panel-for-twitter/assets/5685696/ace7f6a2-5113-486f-b2bc-c80e51ec573f)

- from this tweet: https://twitter.com/itvnews/status/1697016618793017636, but it's happening on all tweets I go into.

I've made sure I've updated the extension to the latest version, and the option to disable the "_Discover more_" section is checked:
![image](https://github.com/insin/control-panel-for-twitter/assets/5685696/acea1cde-5e12-4f05-80ae-a2f8047f72e2)

**Comment by insin** [comment] 2023-08-30 23:49
See #408
