### ISSUE TITLE
settings and backup and export

### ISSUE THREAD

**Issue by subsubsubsubsubsub** [insin/control-panel-for-twitter#395] opened 2023-08-19 22:31 UTC
1. how do I get to the settings?
![image](https://user-images.githubusercontent.com/73518754/261822627-b491c885-7622-4d1b-900f-5d9fbed3b9e3.png) 
2. Extension from the store, will there be a backup of the settings? 
3. I take it there will be no russian language?

**Comment by subsubsubsubsubsub** [comment] 2023-08-19 22:33
> 1. ![image](https://github.com/insin/control-panel-for-twitter/assets/73518754/b491c885-7622-4d1b-900f-5d9fbed3b9e3) how do I get to the settings? 2. extension from the store, will there be a backup of the settings? 3. I take it there will be no Russian language?

**Comment by subsubsubsubsubsub** [comment] 2023-08-19 22:33
> > 1. how do I get to the settings? ![image](https://user-images.githubusercontent.com/73518754/261822627-b491c885-7622-4d1b-900f-5d9fbed3b9e3.png)
2. Extension from the store, will there be a backup of the settings? 
4. I take it there will be no Russian language?

**Comment by insin** [comment] 2023-09-13 03:16
Closing as a duplicate of #204

**Closed by insin** 2023-09-13 03:16 UTC

**Comment by subsubsubsubsubsub** [comment] 2023-09-15 15:23
no answer on how to get in and no backup.
![sshot-006](https://github.com/insin/control-panel-for-twitter/assets/73518754/71ede55e-3982-4024-bd81-7089c2f4d838)
