### ISSUE TITLE
Allow user to save and load the settings as .txt file

### ISSUE THREAD

**Issue by Trimint123** [insin/control-panel-for-twitter#415] opened 2023-09-12 09:45 UTC
Self explanatory. That way, user can copy the settings to other browser, or allowing apps to update without risking the settings to reset to default since some Chromium-base browser cannot update extension from Google Web Store (uninstall and reinstall the extension just to update it).

**Comment by insin** [comment] 2023-09-13 03:18
Closing as a duplicate of #204

You can already export using the debug options (click on the last paragraph in the options 5 times) and we already have some [work in progress on importing](https://github.com/insin/control-panel-for-twitter/tree/import-config), just haven't had the time to finish it and make it easier to access yet

**Closed by insin** 2023-09-13 03:18 UTC
