### ISSUE TITLE
"Upload" and "Gif" buttons are overlapping

### ISSUE THREAD

**Issue by imh1kiko** [insin/control-panel-for-twitter#460] opened 2023-10-29 17:34 UTC
Used to be fine, now they are suddenly overlapping. Possibly due to some change?
Need someone to confirm that it ain't my side.
![firefox_20231029_19_33_04_m5tLhjeZ](https://github.com/insin/control-panel-for-twitter/assets/23316799/7dbaff46-ce21-4aac-9ff0-c8cfedfb6e43)

**Comment by Tagishsimon** [comment] 2023-10-29 23:21
Seems to be the same issue as https://github.com/insin/control-panel-for-twitter/issues/459 - afaics a coding fix is in place, will get rolled out sooner or later.

**Comment by insin** [comment] 2023-10-30 04:55
Closing as a dupe of #459 - this is already fixed, waiting for browser extension stores to review and publish [v3.21.4](https://github.com/insin/control-panel-for-twitter/releases/tag/v3.21.4)

**Closed by insin** 2023-10-30 04:55 UTC
